version: '3.8'

services:
  web:
    build: .
    tty: true
    stdin_open: true
    ports:
      - 4000:4000
      - 50051:50051
    depends_on:
      - postgres
    command: mix phx.server
    volumes:
      - .:/crypto_watcher
    env_file:
     - .env

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
